language: node_js
node_js:
  - '0.10'
before_install:
  - 'ruby --version'
  - 'gem update --system'
  - 'gem install sass'
  - 'gem install compass'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'